plugins {
	id "checkstyle"
	id "java-gradle-plugin"
	id "io.spring.javaformat" version "$javaFormatVersion"
}

repositories {
	mavenCentral()
	gradlePluginPortal()
}

dependencies {
	checkstyle("com.puppycrawl.tools:checkstyle:${checkstyle.toolVersion}")
	checkstyle("io.spring.javaformat:spring-javaformat-checkstyle:${javaFormatVersion}")

	implementation("org.openrewrite.rewrite:org.openrewrite.rewrite.gradle.plugin:7.4.1")
}

gradlePlugin {
	plugins {
		conventionsPlugin {
			id = "org.springframework.ws.conventions"
			implementationClass = "org.springframework.ws.gradle.conventions.ConventionsPlugin"
		}
	}
}

dependencies {
	implementation("io.spring.javaformat:spring-javaformat-gradle-plugin:$javaFormatVersion")
}
